# Use the node image as the base
# ARG baseNodeImageName
# FROM ${baseNodeImageName} AS base
FROM node:20-bookworm AS base

# Set the working directory
WORKDIR /app

# Install Playwright
RUN npm install @playwright/test@1.60.0  

# Install only the necessary Playwright dependencies for Chromium
RUN npx playwright install-deps chromium

# Install only Chromium browser
RUN npx playwright install chromium
