# Use the node image as the base
ARG baseNodeImageName
FROM ${baseNodeImageName} AS base

# Set the working directory
WORKDIR /app

# Install Playwright
RUN npm install @playwright/test@1.59.1

# Install only the necessary Playwright dependencies for WebKit
RUN npx playwright install-deps

# Install only the necessary Playwright dependencies for Chrome
RUN npx -y playwright install
