# Use the node image as the base
FROM node:20-bookworm AS base

# Set the working directory
WORKDIR /app

# Install Playwright
RUN npm install @playwright/test@1.60.0

# Install dependencies for Playwright browsers
RUN npx playwright install-deps

# Install Playwright browsers (chromium, firefox, webkit)
RUN npx -y playwright install
